#ifndef ENUMS_HPP
#define ENUMS_HPP

enum class ZONE_COLORS {CYAN, BLUE, BROWN, GREEN, YELLOW, PURPLE, PINK, NON};
enum class ATTACKING_RANGE {MELEE, RANGED};
enum class FIGHTER_TYPE {HERO, SIDE_KICK};
enum class CARD_EFFECT_TYPE {IMMEDIATE, DURING_COMBAT, AFTER_COMBAT, NONE};
enum class CARD_TYPE {ATTACK, DEFENCE, SCHEME, VERSATILE};
enum class CARD_OWNER {HERO, SIDE_KICK, ANY};
enum class SPACE_OCCUPIED_BY {TEAM1, TEAM2};
enum class HERO_NAME {DRACULA, SHERLOCK};
#endif