#ifndef ENUMS_HPP
#define ENUMS_HPP

enum class ZONE_COLORS {CYAN, BLUE, BROWN, GREEN, YELLOW, PURPLE, PINK, NON};
enum class ATTACKING_RANGE {MELEE, RANGED};
enum class FIGHTER_TYPE {HERO, SIDE_KICK};
enum class CARD_EFFECT_TYPE {IMMEDIATE, DURING_COMBAT, AFTER_COMBAT, NONE};
enum class CARD_TYPE {ATTACK, DEFENCE, SCHEME, VERSATILE};
enum class CARD_OWNER {DRACULA, SHERLOCK, WATSON, SISITERS, ANY};
enum class USER{USER1, USER2, NONE};
enum class HERO_NAME {DRACULA, SHERLOCK};
enum class Dracula_And_Sisters_Array_Index{DRACULA, SIS1, SIS2, SIS3};
enum class Sherlock_And_Watson_Array_Index{SHERLOCK, WATSON};
enum class SideKick_Name {WATSON, DRACULA_SIS1, DRACULA_SIS2, DRACULA_SIS3};
enum class Fighters_Names{SHERLOCK, DRACULA, WATSON, SIS1, SIS2, SIS3, NONE};
enum class cards{AMINISTER_AID,CONFIRM_SUSPICION,COUNTERPUNCH,DEDUCE_STRATEGY,EDUCATION_NEVER_ENDS,ELEMENTARY,ELIMINATE_THE_IMPOSSIBLE,FEINT,FIXED_POINT_IN_A_CHANGING_AGE,
MASTER_OF_DISGUISE,THE_GAME_IS_AFOOT,SERVICE_REVOLVER,STUDY_METHODS,FEEDING_FRENZY,MISTFORM
,AMBUSH,BAPTISM_OF_BLOOD,BEASTFORM,DASH,EXPLOIT,LOOK_INTO_MY_EYES,PREY_UPON,RAVENING_SEDUCTION,THIRST_FOR_SUSTENANCE};
enum class USER_ACTION{USER1_ACTION1, USER1_ACTION2, USER2_ACTION1, USER2_ACTION2};
#endif